### ISSUE TITLE
Script to edit a gitlab file

### ISSUE THREAD

**Issue by emepetres** [MSO4SC/MSOPortal#110]
Following #102, build python script that will:

1.- Receive the username, the parent gitlab repository (the original repository) and the file name to be edited.
2.- Check if the repository exists for this user in gitlab
2.1.- If the repository does not exists, fork it from the parent repository to the user space.
3.- Return a url to edit the file in the user repository.

**Comment by ncde** [comment]
Hello, 
I wrote the  following script that takes a remote repository url, username and folder name
if the folder name already exists it assumes the remote repository was cloned previously
otherwise clones it

then it checks if a branch with students/user_name exists if yes checks out to that branch
otherwise creates a new branch

the file that needs to be edited is now in the folder_name/file 

the example uses the python package gitpython
----------------------------------------------------------------------------------------

import git

def createrepo(repo_url, user_name, folder_name):
	try:
		repo = git.Repo.clone_from(repo_url, folder_name)
	except: 
		repo = git.Repo(folder_name)


	gitc = repo.git
	for remote in repo.remotes:
	  	remote.fetch()
	
	br_user = None
	for br in repo.branches:
		if br.name == 'students/{}'.format(user_name):
			br_user = br
			break

	if br_user == None:
		gitc.checkout('-b', 'students/{}'.format(user_name))
	else:
		gitc.checkout('students/{}'.format(user_name))



if __name__ == "__main__":
	print createrepo("https://gitlab.srv.cesga.es/ncde/Unicorn", 'test_user', 'unicorn_folder')
