### ISSUE TITLE
who and how are defined seller within MarketPlace

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#62]
I've created a catalog, a product and an offering.
I'm the owner of the offering but not seller!

How can I become the seller of this offering?
What is the generic procedure to define/declare a seller?

**Comment by emepetres** [comment]
What do you mean with that "you are not a seller"? Actually you are a seller because you can create offers and products...
What are you trying to do?

**Comment by prudhomm** [comment]
I think @Trophime  means that he is owning the offering as a developer but the seller is an organization to which @Trophime  and @Trophime institution belongs to.
For example I may own a feel++ toolbox app, but the seller is the organisation Cemosis and it is Cemosis which should receive the money

**Comment by emepetres** [comment]
I understand, I think it is possible to do something like that. 

Let me think which could be the simplest way.

**Comment by emepetres** [comment]
Ok, so you can create a new organization in the IDM, and then "authorize" all the users in this organization to be "Sellers". That means that an user on the marketplace an register a product on behalf of the organization, and the owner of the product would be this organization.

The problem is that the portal is treating organization as users entities (like is doing the marketplace). I see two possible solutions:
1.- Create an user in the IDM that will represent your organization.
2.- Add to the portal the feature to change from "user" login to "organization" login, in which the user will act in the portal on behalf of that organization.

For now you can do the work around with the first option. I will create another issue to implement the second.
